#!/usr/bin/python
##
# This file is part of CimCity.
#
# CimCity is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CimCity is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CimCity.  If not, see <http://www.gnu.org/licenses/>.
##

import time
import settings
import sys

from items.person import Person

version = "0.0.1"

def alive(people):
    return len([p for p in people if not p.dead])

def dead(people):
    return len([p for p in people if p.dead])

def display(msg):
    def clear():
        print " "*80  + " \r",

    print " %s\r" % msg + "",
    sys.stdout.flush()

if __name__ == "__main__":
    if "-v" in sys.argv[1:] or "--version" in sys.argv[1:]:
        print "The version is: %s" % version
        sys.exit()

    if len(sys.argv) <= 1:
        print "You need to say how many people to start off with"
        print "Usage:  %s <people>" % sys.argv[0]
        sys.exit()

    # inital people gen
    people = [Person() for i in range(int(sys.argv[1]))]
    c = 0
    ticks = 0
    speed = float(60) / settings.speed
    while True:
        display("Alive: %s | Dead: %s | ticks %s" % (alive(people), dead(people), ticks))
        # main game loop
        try:
            person = people[c]
        except IndexError:
            ticks += 1
            time.sleep(speed)
            c = 0
            continue

        c += 1
        try:
            np = person.on_tick(people[c])
        except IndexError:
            np = person.on_tick()
        
        if np:
            people.append(np)

